/* MakanAI World V9 — 24-feature Innovation Hub */
(function(){
  const FEATURES=[
    {id:'body-progress',n:1,icon:'📸',title:'AI Body Progress',subtitle:'Private progress photos and measurements',cat:'lifestyle'},
    {id:'portion-camera',n:2,icon:'📏',title:'Smart Portion Camera',subtitle:'Estimate serving size with a reference object',cat:'scan'},
    {id:'live-ar',n:3,icon:'🥽',title:'Live AR Food Scanner',subtitle:'Camera overlay with food and nutrition',cat:'scan'},
    {id:'voice-log',n:4,icon:'🎙️',title:'Voice Food Logging',subtitle:'Speak meals in English, BM or Manglish',cat:'scan'},
    {id:'whatsapp-log',n:5,icon:'💬',title:'WhatsApp Food Logging',subtitle:'Prepare and parse WhatsApp meal messages',cat:'social'},
    {id:'delivery-mode',n:6,icon:'🛵',title:'Healthy Delivery Mode',subtitle:'Delivery ideas based on calories and budget',cat:'lifestyle'},
    {id:'plate-builder',n:7,icon:'🍽️',title:'Smart Plate Builder',subtitle:'Build a balanced plate visually',cat:'lifestyle'},
    {id:'nutrition-battle',n:8,icon:'⚔️',title:'Nutrition Battle',subtitle:'Compete with friends using healthy challenges',cat:'social'},
    {id:'virtual-pet',n:9,icon:'🐣',title:'Food Avatar & Pet',subtitle:'Raise a pet through healthy habits',cat:'social'},
    {id:'mood-food',n:10,icon:'🙂',title:'Mood & Food Tracker',subtitle:'Discover eating patterns by mood',cat:'lifestyle'},
    {id:'sleep-hunger',n:11,icon:'😴',title:'Sleep & Hunger Analysis',subtitle:'Compare sleep, hunger and snack patterns',cat:'lifestyle'},
    {id:'cycle-mode',n:12,icon:'🌙',title:'Cycle Nutrition Mode',subtitle:'Optional private cycle and craving log',cat:'lifestyle'},
    {id:'travel-food',n:13,icon:'✈️',title:'Travel Food Mode',subtitle:'Local foods and dietary phrases abroad',cat:'travel'},
    {id:'leftover-generator',n:14,icon:'♻️',title:'Leftover Recipe Generator',subtitle:'Turn remaining ingredients into meals',cat:'lifestyle'},
    {id:'budget-challenge',n:15,icon:'💰',title:'Smart Budget Challenge',subtitle:'Track spending and cost-efficient nutrition',cat:'lifestyle'},
    {id:'campus-marketplace',n:16,icon:'🎓',title:'Campus Food Marketplace',subtitle:'Canteen menus, prices, queues and preorder',cat:'campus'},
    {id:'nutrition-quiz',n:17,icon:'🧠',title:'Nutrition Quiz',subtitle:'Learn portions, labels and food choices',cat:'campus'},
    {id:'ingredient-safety',n:18,icon:'🛡️',title:'Ingredient Safety Scanner',subtitle:'Flag possible allergens and label terms',cat:'scan'},
    {id:'group-ordering',n:19,icon:'👥',title:'Restaurant Group Ordering',subtitle:'Find menu choices suitable for everyone',cat:'social'},
    {id:'nutrition-passport',n:20,icon:'🪪',title:'Digital Nutrition Passport',subtitle:'Optional QR allergy and dietary card',cat:'travel'},
    {id:'health-report',n:21,icon:'📄',title:'AI Health Report PDF',subtitle:'Weekly and monthly nutrition summaries',cat:'lifestyle'},
    {id:'food-authenticity',n:22,icon:'🏺',title:'Food Culture & Authenticity',subtitle:'Origin, ingredients and healthier preparation',cat:'travel'},
    {id:'smart-kitchen',n:23,icon:'⚖️',title:'Smart Kitchen Integration',subtitle:'Simulated scales, bottles, fridges and cookers',cat:'scan'},
    {id:'creator-portal',n:24,icon:'🏪',title:'Creator & Business Portal',subtitle:'Submit menus, recipes and products for review',cat:'business'}
  ];
  const QUIZ=[
    {q:'Which usually has less added sugar?',a:['Teh tarik','Plain water','Soft drink','Milkshake'],c:1,e:'Plain water contains no added sugar.'},
    {q:'A balanced plate commonly gives the largest area to:',a:['Vegetables','Sauce','Dessert','Fried snacks'],c:0,e:'Vegetables commonly make up about half of a balanced plate.'},
    {q:'Which nutrient is most associated with muscle repair?',a:['Protein','Sodium','Added sugar','Alcohol'],c:0,e:'Protein supplies amino acids used in tissue repair.'},
    {q:'For a packaged product, serving size is important because:',a:['It changes the brand','Nutrition values may be per serving','It proves the food is healthy','It guarantees halal status'],c:1,e:'Labels often report nutrients per serving, not the entire package.'},
    {q:'Which is usually the best hydration choice?',a:['Energy drink','Plain water','Sweetened tea','Soda'],c:1,e:'Plain water hydrates without extra sugar or calories.'},
    {q:'A high-sodium food may be better balanced by:',a:['More salty sauce','Fresh vegetables and water','Extra processed meat','A sugary drink'],c:1,e:'Fresh foods and water can help keep the overall meal less sodium-heavy.'},
    {q:'Which is a practical portion reference?',a:['A known-size spoon or card','The food colour','Restaurant music','Phone brightness'],c:0,e:'A known-size object helps estimate scale in an image.'},
    {q:'For a severe allergy, an app result should be:',a:['Treated as a guarantee','Verified with packaging or staff','Ignored completely','Shared publicly'],c:1,e:'Always verify ingredients and cross-contamination with reliable sources.'}
  ];
  const CAMPUS_STALLS=[
    {id:'c1',name:'Campus Nasi Campur',emoji:'🍛',place:'Student Centre',queue:8,open:true,foods:[['Rice + grilled chicken + vegetables',8.5,540],['Rice + fried chicken',7.5,720],['Vegetable rice set',6.5,460]]},
    {id:'c2',name:'Healthy Bowl Kiosk',emoji:'🥗',place:'Library Café',queue:3,open:true,foods:[['Chicken grain bowl',12,510],['Tofu vegetable bowl',10,430],['Fruit yogurt cup',5,260]]},
    {id:'c3',name:'Mamak Express',emoji:'🫓',place:'College Block',queue:12,open:true,foods:[['Roti canai + dhal',3.5,390],['Thosai + chutney',4.5,330],['Mee goreng',6.5,610]]},
    {id:'c4',name:'Quick Bites',emoji:'🥪',place:'Faculty Lobby',queue:1,open:false,foods:[['Tuna sandwich',6,360],['Egg sandwich',5,340],['Mineral water',1.5,0]]}
  ];
  const TRAVEL_PHRASES={
    Japan:['Does this contain peanuts? — Kore ni pīnattsu wa haitte imasu ka?','I cannot eat shellfish — Kōkakurui wa taberaremasen','Is there pork or alcohol? — Butaniku matawa arukōru wa arimasu ka?'],
    Korea:['Does this contain nuts? — Gyeongwallyu-ga deureo issnayo?','I cannot eat shellfish — Jogaeryu-reul meokji mothaeyo','No pork, please — Dwaejigogi ppae juseyo'],
    China:['Does this contain peanuts? — Zhè ge yǒu huāshēng ma?','I cannot eat shellfish — Wǒ bù néng chī bèiké lèi','No pork, please — Qǐng bú yào zhūròu'],
    France:['Does this contain peanuts? — Est-ce que cela contient des cacahuètes ?','I cannot eat shellfish — Je ne peux pas manger de fruits de mer','No alcohol, please — Sans alcool, s’il vous plaît'],
    Spain:['Does this contain peanuts? — ¿Contiene cacahuetes?','I cannot eat shellfish — No puedo comer mariscos','No pork, please — Sin cerdo, por favor'],
    Italy:['Does this contain peanuts? — Contiene arachidi?','I cannot eat shellfish — Non posso mangiare crostacei','No alcohol, please — Senza alcol, per favore'],
    Malaysia:['Adakah ini mengandungi kacang?','Saya tidak boleh makan makanan laut bercengkerang','Adakah makanan ini halal?'],
    default:['Does this contain my allergen?','Please prepare this without pork or alcohol.','Could you show me the ingredient list?']
  };
  const SAFETY_RULES=[
    {term:/peanut|groundnut|kacang tanah/i,label:'Possible peanut ingredient',level:'danger'},
    {term:/milk|whey|casein|lactose|susu/i,label:'Possible milk ingredient',level:'warn'},
    {term:/egg|albumen|telur/i,label:'Possible egg ingredient',level:'warn'},
    {term:/soy|soya|kedelai/i,label:'Possible soy ingredient',level:'warn'},
    {term:/shrimp|prawn|crab|lobster|shellfish|udang|ketam/i,label:'Possible shellfish ingredient',level:'danger'},
    {term:/wheat|gluten|barley|rye|gandum/i,label:'Possible gluten-containing grain',level:'warn'},
    {term:/pork|bacon|ham|lard|gelatin|porcine/i,label:'Possible pork or animal-derived ingredient',level:'danger'},
    {term:/sugar|syrup|maltose|dextrose|fructose|glucose/i,label:'Added sugar term detected',level:'info'},
    {term:/sodium|salt|msg|monosodium/i,label:'Sodium-related ingredient detected',level:'info'},
    {term:/aspartame|sucralose|acesulfame|saccharin/i,label:'Artificial sweetener term detected',level:'info'}
  ];

  function ensureMegaState(){
    state.innovation=Object.assign({
      bodyProgress:[],battles:[],pet:{name:'Momo',energy:55,happiness:55,stage:1,outfit:'none'},
      moods:[],sleep:[],cycle:{enabled:false,logs:[]},budget:{target:140,manual:[]},campusOrders:[],
      quiz:{index:0,score:0,answered:false},passport:{},devices:[],submissions:[],groupMembers:[],
      plate:{veg:50,protein:25,carb:25},voiceHistory:[],whatsappHistory:[]
    },state.innovation||{});
    const i=state.innovation;
    ['bodyProgress','battles','moods','sleep','campusOrders','devices','submissions','groupMembers','voiceHistory','whatsappHistory'].forEach(k=>i[k]=Array.isArray(i[k])?i[k]:[]);
    i.cycle=Object.assign({enabled:false,logs:[]},i.cycle||{});i.cycle.logs=Array.isArray(i.cycle.logs)?i.cycle.logs:[];
    i.budget=Object.assign({target:140,manual:[]},i.budget||{});i.budget.manual=Array.isArray(i.budget.manual)?i.budget.manual:[];
    i.pet=Object.assign({name:'Momo',energy:55,happiness:55,stage:1,outfit:'none'},i.pet||{});
    i.quiz=Object.assign({index:0,score:0,answered:false},i.quiz||{});
    i.passport=Object.assign({},i.passport||{});
  }
  ensureMegaState();
  const oldPersist=persist;
  persist=function(){localStorage.setItem('makanaiWorldV9',JSON.stringify(state));oldPersist();};

  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const money=value=>`RM ${Number(value||0).toFixed(2)}`;
  const today=()=>dayKey();
  function addXP(n,reason){if(typeof awardXP==='function')awardXP(n,reason,false);else{state.xp=(state.xp||0)+n;persist();}}
  function closeModal(){stopARCamera();$('#innovationModal').classList.add('hidden');document.body.classList.remove('modal-open');}
  function openFeature(id){
    const f=FEATURES.find(x=>x.id===id);if(!f)return;
    $('#innovationModalIcon').textContent=f.icon;$('#innovationModalNumber').textContent=`FEATURE ${f.n} OF 24 · ${f.cat.toUpperCase()}`;
    $('#innovationModalTitle').textContent=f.title;$('#innovationModalSubtitle').textContent=f.subtitle;
    $('#innovationWorkspace').innerHTML=workspace(id);$('#innovationModal').classList.remove('hidden');document.body.classList.add('modal-open');
    bindFeature(id);$('#innovationWorkspace').scrollTop=0;
  }
  function renderGrid(){
    const term=($('#innovationSearch')?.value||'').toLowerCase();const active=$('#innovationFilters .active')?.dataset.innovationFilter||'all';
    const list=FEATURES.filter(f=>(active==='all'||f.cat===active)&&`${f.title} ${f.subtitle}`.toLowerCase().includes(term));
    $('#innovationGrid').innerHTML=list.map(f=>`<button class="innovation-card" data-feature="${f.id}"><span class="innovation-number">${String(f.n).padStart(2,'0')}</span><div class="innovation-card-icon">${f.icon}</div><div><small>${f.cat}</small><h3>${f.title}</h3><p>${f.subtitle}</p></div><i>Open →</i></button>`).join('')||'<div class="empty">No feature matches this search.</div>';
    $$('[data-feature]').forEach(b=>b.addEventListener('click',()=>openFeature(b.dataset.feature)));
  }
  function workspace(id){return ({
    'body-progress':bodyProgressHTML,'portion-camera':portionHTML,'live-ar':arHTML,'voice-log':voiceHTML,'whatsapp-log':whatsappHTML,
    'delivery-mode':deliveryHTML,'plate-builder':plateHTML,'nutrition-battle':battleHTML,'virtual-pet':petHTML,'mood-food':moodHTML,
    'sleep-hunger':sleepHTML,'cycle-mode':cycleHTML,'travel-food':travelHTML,'leftover-generator':leftoverHTML,'budget-challenge':budgetHTML,
    'campus-marketplace':campusHTML,'nutrition-quiz':quizHTML,'ingredient-safety':safetyHTML,'group-ordering':groupHTML,
    'nutrition-passport':passportHTML,'health-report':reportHTML,'food-authenticity':authenticityHTML,'smart-kitchen':kitchenHTML,
    'creator-portal':creatorHTML
  })[id]();}
  const section=(title,body)=>`<section class="mega-section"><div class="mega-section-title"><h3>${title}</h3></div>${body}</section>`;
  const infoNote=text=>`<p class="mega-note">${text}</p>`;

  function bodyProgressHTML(){const entries=state.innovation.bodyProgress;return section('Private progress entry',`<form id="bodyProgressForm" class="mega-form"><div class="mega-upload-pair"><label><b>Front photo</b><input id="bodyFront" type="file" accept="image/*" capture="user"><span>📷 Add front photo</span></label><label><b>Side photo</b><input id="bodySide" type="file" accept="image/*" capture="user"><span>📷 Add side photo</span></label></div><div class="mega-grid-3"><label>Date<input id="bodyDate" type="date" value="${today()}"></label><label>Weight (kg)<input id="bodyWeight" type="number" step=".1"></label><label>Waist (cm)<input id="bodyWaist" type="number" step=".1"></label></div><label>Private note<textarea id="bodyNote" rows="2" placeholder="How you felt, clothing consistency, lighting…"></textarea></label><button class="primary">Save private entry</button></form>${infoNote('Photos are compressed and stored only in this browser. This feature tracks visual progress and measurements; it does not diagnose health or body composition.')}`)+section('Progress timeline',`<div id="bodyTimeline" class="body-timeline">${entries.length?entries.map(bodyEntryCard).join(''):'<div class="empty">No private entries yet.</div>'}</div>`);}
  function bodyEntryCard(e){return `<article><div class="body-thumbs">${e.front?`<img src="${e.front}" alt="Front progress">`:''}${e.side?`<img src="${e.side}" alt="Side progress">`:''}</div><div><b>${esc(e.date)}</b><span>${e.weight?`${e.weight} kg`:''}${e.waist?` · ${e.waist} cm waist`:''}</span><p>${esc(e.note||'')}</p></div><button class="remove" data-delete-body="${e.id}">×</button></article>`;}
  function portionHTML(){return section('Photo and scale reference',`<div class="mega-camera-box"><input id="portionImage" type="file" accept="image/*" capture="environment"><img id="portionPreview" class="hidden"><div id="portionPrompt"><span>📏</span><b>Take a meal photo</b><small>Place a known object near the food.</small></div></div><div class="mega-grid-2"><label>Food name<input id="portionFood" list="foodNames" placeholder="Example: white rice"></label><label>Reference object<select id="portionReference"><option value="card">Bank card (85.6 mm)</option><option value="spoon">Tablespoon</option><option value="fork">Dinner fork</option><option value="plate">Standard 25 cm plate</option></select></label></div><button id="estimatePortion" class="primary">Estimate portion</button><div id="portionResult"></div>${infoNote('Photo estimates can be wrong because depth, ingredients and camera angle vary. Confirm grams or serving size before saving.')}`);}
  function arHTML(){return section('Live camera overlay',`<div class="ar-stage"><video id="arVideo" playsinline muted></video><canvas id="arCanvas" class="hidden"></canvas><div id="arPlaceholder"><span>🥽</span><b>Live scanner ready</b><small>Camera permission requires HTTPS or localhost.</small></div><div class="ar-reticle"></div><div id="arOverlay" class="ar-overlay hidden"></div></div><div class="mega-action-row"><button id="startAR" class="primary">Start camera</button><button id="captureAR" class="soft" disabled>Capture & analyse</button><button id="stopAR" class="link" disabled>Stop</button></div>${infoNote('Live overlay uses captured frames rather than continuous medical-grade measurement. Confirm every detected item.')}`);}
  function voiceHTML(){return section('Speak your meal',`<div class="voice-orb" id="voiceOrb">🎙️</div><p id="voiceStatus" class="center-text">Tap the microphone and say: “I ate two roti canai and one teh tarik.”</p><div class="mega-action-row center-actions"><button id="startVoice" class="primary">Start listening</button><button id="stopVoice" class="soft">Stop</button></div><label>Transcript<textarea id="voiceTranscript" rows="3" placeholder="Your speech appears here. You can edit it."></textarea></label><button id="parseVoice" class="soft full">Find foods and log</button><div id="voiceMatches"></div>`)+section('Recent voice logs',`<div id="voiceHistory" class="mini-history"></div>`);}
  function whatsappHTML(){return section('WhatsApp-style meal message',`<div class="whatsapp-preview"><span>💬</span><p>Send or paste a message such as:<br><b>Lunch tadi nasi ayam satu dan teh tarik.</b></p></div><label>Meal message<textarea id="whatsappText" rows="3" placeholder="Type a meal message…"></textarea></label><div class="mega-action-row"><button id="analyseWhatsApp" class="primary">Analyse & log locally</button><button id="openWhatsApp" class="soft">Open WhatsApp share</button></div><div id="whatsappMatches"></div>${infoNote('This edition prepares WhatsApp messages and parses pasted text locally. Receiving messages automatically would require a separately configured business bot and webhook.')}`);}
  function deliveryHTML(){const left=Math.max(0,state.target-totals().calories);return section('Healthy delivery recommendations',`<div class="delivery-summary"><div><span>Calories left</span><b>${left} kcal</b></div><div><span>Meal budget</span><b>${money((state.profile.dailyBudget||30)*.45)}</b></div><div><span>Diet</span><b>${esc(state.profile.dietStyle||'balanced')}</b></div></div><div class="mega-grid-3"><label>Meal<select id="deliveryMeal"><option>Dinner</option><option>Lunch</option><option>Breakfast</option><option>Snack</option></select></label><label>Maximum calories<input id="deliveryCalories" type="number" value="${Math.max(250,Math.min(700,left||600))}"></label><label>Maximum price (RM)<input id="deliveryBudget" type="number" value="${Math.max(8,Math.round((state.profile.dailyBudget||30)*.45))}"></label></div><button id="findDelivery" class="primary">Find delivery ideas</button><div id="deliveryResults" class="delivery-grid"></div>`);}
  function plateHTML(){const p=state.innovation.plate;return section('Build your plate',`<div class="plate-layout"><div class="smart-plate"><div id="plateVeg" class="plate-segment veg"><span>🥦</span><b>Vegetables</b></div><div id="plateProtein" class="plate-segment protein"><span>🍗</span><b>Protein</b></div><div id="plateCarb" class="plate-segment carb"><span>🍚</span><b>Carbs</b></div></div><div class="plate-controls"><label>Vegetables <b id="vegValue">${p.veg}%</b><input id="vegSlider" type="range" min="0" max="100" value="${p.veg}"></label><label>Protein <b id="proteinValue">${p.protein}%</b><input id="proteinSlider" type="range" min="0" max="100" value="${p.protein}"></label><label>Carbohydrates <b id="carbValue">${p.carb}%</b><input id="carbSlider" type="range" min="0" max="100" value="${p.carb}"></label></div></div><div id="plateScore" class="plate-score"></div><button id="logPlate" class="primary">Log balanced plate</button>`);}
  function battleHTML(){return section('Create a battle',`<form id="battleForm" class="mega-form"><div class="mega-grid-3"><label>Friend name<input id="battleFriend" required></label><label>Challenge<select id="battleType"><option value="water">Water goal</option><option value="fruit">Fruit & vegetable choices</option><option value="logging">Meal logging</option><option value="sugar">Choose water over sweet drinks</option></select></label><label>Target<input id="battleTarget" type="number" min="1" value="5"></label></div><button class="primary">Start battle</button></form>`)+section('Active battles',`<div id="battleList" class="battle-list"></div>`);}
  function petHTML(){const pet=state.innovation.pet;return section('Your wellness pet',`<div class="pet-room"><div class="pet-sparkles">✦　✧　✦</div><div id="petAvatar" class="pet-avatar">${petEmoji()}</div><h3 id="petNameLabel">${esc(pet.name)}</h3><span>Stage ${pet.stage}</span><div class="pet-meters"><label>Energy <i><b id="petEnergy" style="width:${pet.energy}%"></b></i><span>${pet.energy}%</span></label><label>Happiness <i><b id="petHappy" style="width:${pet.happiness}%"></b></i><span>${pet.happiness}%</span></label></div></div><div class="mega-grid-2"><label>Pet name<input id="petName" value="${esc(pet.name)}"></label><label>Outfit<select id="petOutfit"><option value="none">No outfit</option><option value="cap" ${pet.outfit==='cap'?'selected':''}>Cap</option><option value="crown" ${pet.outfit==='crown'?'selected':''}>Crown</option><option value="glasses" ${pet.outfit==='glasses'?'selected':''}>Glasses</option></select></label></div><div class="pet-actions"><button data-pet-action="water">💧 Give water</button><button data-pet-action="fruit">🍎 Feed fruit</button><button data-pet-action="walk">🚶 Go walking</button><button data-pet-action="sleep">😴 Rest</button></div>${infoNote('The pet is a motivation game. It does not judge food or replace real health guidance.')}`);}
  function moodHTML(){return section('Log mood and eating context',`<form id="moodForm" class="mega-form"><div class="mood-picker">${['😊 Happy','😣 Stressed','😴 Tired','😐 Bored','😢 Sad','🤩 Excited'].map((x,i)=>`<label><input type="radio" name="mood" value="${x}" ${i===0?'checked':''}><span>${x}</span></label>`).join('')}</div><div class="mega-grid-3"><label>Hunger (1–5)<input id="moodHunger" type="range" min="1" max="5" value="3"></label><label>Meal / craving<input id="moodMeal" placeholder="Example: chocolate"></label><label>Time<select id="moodTime"><option>Morning</option><option>Afternoon</option><option>Evening</option><option>Late night</option></select></label></div><label>Note<textarea id="moodNote" rows="2"></textarea></label><button class="primary">Save mood entry</button></form>`)+section('Pattern summary',`<div id="moodSummary"></div><div id="moodHistory" class="mini-history"></div>`);}
  function sleepHTML(){return section('Sleep and appetite log',`<form id="sleepForm" class="mega-form"><div class="mega-grid-3"><label>Sleep hours<input id="sleepHours" type="number" step=".25" min="0" max="16" value="7"></label><label>Morning hunger (1–5)<input id="sleepHunger" type="number" min="1" max="5" value="3"></label><label>Snack count<input id="sleepSnacks" type="number" min="0" value="1"></label></div><div class="mega-grid-2"><label>Bedtime<input id="sleepBed" type="time" value="23:30"></label><label>Wake time<input id="sleepWake" type="time" value="07:00"></label></div><button class="primary">Save sleep log</button></form>`)+section('Observation',`<div id="sleepAnalysis"></div><div id="sleepHistory" class="mini-history"></div>`);}
  function cycleHTML(){const c=state.innovation.cycle;return section('Private optional mode',`<label class="mega-toggle"><input id="cycleEnabled" type="checkbox" ${c.enabled?'checked':''}><span>Enable private cycle nutrition mode</span></label><div id="cycleFormWrap" class="${c.enabled?'':'hidden'}"><form id="cycleForm" class="mega-form"><div class="mega-grid-3"><label>Cycle day<input id="cycleDay" type="number" min="1" max="60" value="1"></label><label>Phase<select id="cyclePhase"><option>Menstrual</option><option>Follicular</option><option>Ovulation</option><option>Luteal</option><option>Unsure</option></select></label><label>Energy (1–5)<input id="cycleEnergy" type="number" min="1" max="5" value="3"></label></div><label>Cravings / symptoms<input id="cycleCraving" placeholder="Optional"></label><button class="primary">Save private log</button></form></div>${infoNote('This mode is optional and stored locally. Suggestions are general wellness reminders and are not cycle prediction, contraception or medical advice.')}`)+section('Recent logs',`<div id="cycleHistory" class="mini-history"></div>`);}
  function travelHTML(){const countries=[...new Set(allFoods().map(f=>f.country).filter(Boolean))].sort();return section('Choose destination',`<div class="mega-grid-2"><label>Destination<select id="travelCountry">${countries.map(c=>`<option ${c==='Japan'?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label>Need<select id="travelNeed"><option value="allergy">Allergy support</option><option value="halal">Halal-friendly phrases</option><option value="vegetarian">Vegetarian phrases</option><option value="budget">Budget food ideas</option></select></label></div><button id="buildTravel" class="primary">Build travel food guide</button><div id="travelGuide"></div>`);}
  function leftoverHTML(){const pantry=(state.shop?.pantry||[]);return section('Select leftovers',`<div class="leftover-items">${pantry.length?pantry.map(x=>`<label><input type="checkbox" value="${esc(x.name)}" checked><span>${x.emoji||'🥫'} ${esc(x.name)}</span></label>`).join(''):'<p class="mega-note">No pantry items found. Type leftovers below.</p>'}</div><label>Other leftovers<input id="leftoverManual" placeholder="Rice, eggs, chicken, vegetables"></label><div class="mega-grid-2"><label>Maximum time<select id="leftoverTime"><option value="15">15 minutes</option><option value="30">30 minutes</option><option value="45">45 minutes</option></select></label><label>Style<select id="leftoverStyle"><option>Quick meal</option><option>High protein</option><option>Vegetarian</option><option>Lower calorie</option></select></label></div><button id="generateLeftover" class="primary">Generate leftover recipes</button><div id="leftoverResults" class="delivery-grid"></div>`);}
  function budgetHTML(){return section('Weekly food budget',`<div class="budget-ring" id="budgetRing"><div><b id="budgetSpent">${money(budgetSpent())}</b><span>spent</span></div></div><div class="mega-grid-2"><label>Weekly target (RM)<input id="budgetTarget" type="number" value="${state.innovation.budget.target}"></label><form id="budgetEntryForm" class="inline"><input id="budgetEntryName" placeholder="Meal or purchase" required><input id="budgetEntryAmount" type="number" step=".01" placeholder="RM" required><button class="soft">Add</button></form></div><div id="budgetInsight"></div>`)+section('Spending entries',`<div id="budgetEntries" class="mini-history"></div>`);}
  function campusHTML(){return section('Campus marketplace',`<div class="campus-toolbar"><input id="campusSearch" placeholder="Search stall or food"><select id="campusBudget"><option value="999">Any price</option><option value="5">Under RM5</option><option value="10" selected>Under RM10</option><option value="15">Under RM15</option></select><select id="campusQueue"><option value="999">Any queue</option><option value="5">Under 5 min</option><option value="10">Under 10 min</option></select></div><div id="campusGrid" class="campus-grid"></div>`)+section('My preorders',`<div id="campusOrders" class="mini-history"></div>`);}
  function quizHTML(){return section('Nutrition learning challenge',`<div id="quizBox" class="quiz-box"></div><div class="quiz-stats"><span>Score <b id="quizScore">${state.innovation.quiz.score}</b></span><span>Question <b id="quizNumber">1</b> / ${QUIZ.length}</span></div>`);}
  function safetyHTML(){return section('Ingredient list scanner',`<div class="mega-upload-compact"><input id="safetyImage" type="file" accept="image/*" capture="environment"><span>📷 Upload ingredient label photo</span></div><label>Ingredient text<textarea id="safetyText" rows="5" placeholder="Paste ingredients here…"></textarea></label><button id="scanIngredients" class="primary">Check ingredient terms</button><div id="safetyResults"></div>${infoNote('Keyword detection can miss synonyms, cross-contamination and manufacturing changes. For severe allergies, verify the current packaging and contact the manufacturer or restaurant.')}`);}
  function groupHTML(){return section('Group dietary needs',`<form id="groupForm" class="mega-form"><div class="mega-grid-3"><label>Name<input id="groupName" required></label><label>Preference<select id="groupPreference"><option>Balanced</option><option>Halal-friendly</option><option>Vegetarian</option><option>Vegan</option><option>Lower calorie</option></select></label><label>Allergy<input id="groupAllergy" placeholder="Optional"></label></div><button class="primary">Add person</button></form><div id="groupMembers"></div>`)+section('Menu matches for the group',`<button id="matchGroup" class="soft full">Find suitable shared choices</button><div id="groupResults" class="delivery-grid"></div>`);}
  function passportHTML(){const p=state.innovation.passport;return section('Create an optional safety card',`<form id="passportForm" class="mega-form"><div class="mega-grid-2"><label>Display name<input id="passportName" value="${esc(p.name||state.profile.name||'')}"></label><label>Language<select id="passportLanguage"><option>English</option><option>Bahasa Melayu</option><option>中文</option><option>日本語</option><option>한국어</option><option>العربية</option></select></label></div><label>Allergies / foods to avoid<input id="passportAllergy" value="${esc(p.allergy||state.profile.allergy||'')}"></label><label>Diet preference<input id="passportDiet" value="${esc(p.diet||state.profile.dietStyle||'')}"></label><label>Emergency contact<input id="passportContact" value="${esc(p.contact||'')}"></label><label class="mega-toggle"><input id="passportConsent" type="checkbox"><span>I understand the selected information will be encoded into a QR card.</span></label><button class="primary">Generate nutrition passport</button></form><div id="passportResult"></div>${infoNote('Only include information you are comfortable sharing. A QR card is not a substitute for medical identification or restaurant verification.')}`);}
  function reportHTML(){return section('Generate a report',`<div class="report-preview" id="reportPreview"></div><div class="mega-grid-2"><label>Period<select id="reportPeriod"><option value="7">Last 7 days</option><option value="30">Last 30 days</option></select></label><label>Include<select id="reportInclude"><option value="nutrition">Nutrition and progress</option><option value="full">Full report with budget and mood</option></select></label></div><div class="mega-action-row"><button id="downloadReport" class="primary">Download PDF</button><button id="printReport" class="soft">Print fallback</button></div>${infoNote('The report summarises user-entered estimates and is not a clinical report or diagnosis.')}`);}
  function authenticityHTML(){return section('Explore a food',`<div class="mega-grid-2"><label>Food search<input id="authFood" list="foodNames" placeholder="Example: nasi lemak"></label><button id="exploreFood" class="primary align-end">Explore origin & preparation</button></div><div id="authResult"></div>`);}
  function kitchenHTML(){return section('Connected kitchen devices',`<form id="deviceForm" class="mega-form"><div class="mega-grid-3"><label>Device name<input id="deviceName" placeholder="Kitchen Scale" required></label><label>Type<select id="deviceType"><option>Smart scale</option><option>Smart water bottle</option><option>Smart refrigerator</option><option>Air fryer</option><option>Fitness watch</option></select></label><label>Status<select id="deviceStatus"><option>Connected</option><option>Demo mode</option></select></label></div><button class="primary">Pair device</button></form><div id="deviceList"></div>`)+section('Live demo controls',`<div class="kitchen-console"><label>Scale reading (g)<input id="scaleReading" type="number" value="180"></label><label>Food<input id="scaleFood" list="foodNames" value="White rice"></label><button id="logScale" class="soft">Log weighed food</button><label>Air fryer timer (min)<input id="fryerMinutes" type="number" value="15"></label><button id="startFryer" class="soft">Start timer</button><div id="kitchenStatus"></div></div>`);}
  function creatorHTML(){return section('Submit food or business data',`<form id="creatorForm" class="mega-form"><div class="mega-grid-3"><label>Submission type<select id="creatorType"><option>Restaurant menu</option><option>Packaged product</option><option>Community recipe</option><option>Campus stall</option></select></label><label>Business / creator<input id="creatorName" required></label><label>Country<input id="creatorCountry" value="Malaysia"></label></div><label>Item or menu name<input id="creatorItem" required></label><div class="mega-grid-3"><label>Calories<input id="creatorCalories" type="number"></label><label>Price<input id="creatorPrice" type="number" step=".01"></label><label>Barcode / certificate ref<input id="creatorReference"></label></div><label>Description<textarea id="creatorDescription" rows="3"></textarea></label><button class="primary">Submit for review</button></form>${infoNote('Community and business data should remain marked unverified until supporting evidence is reviewed.')}`)+section('Review queue',`<div id="submissionList"></div>`);}

  function bindFeature(id){
    const map={
      'body-progress':bindBody,'portion-camera':bindPortion,'live-ar':bindAR,'voice-log':bindVoice,'whatsapp-log':bindWhatsApp,'delivery-mode':bindDelivery,'plate-builder':bindPlate,'nutrition-battle':bindBattle,'virtual-pet':bindPet,'mood-food':bindMood,'sleep-hunger':bindSleep,'cycle-mode':bindCycle,'travel-food':bindTravel,'leftover-generator':bindLeftover,'budget-challenge':bindBudget,'campus-marketplace':bindCampus,'nutrition-quiz':bindQuiz,'ingredient-safety':bindSafety,'group-ordering':bindGroup,'nutrition-passport':bindPassport,'health-report':bindReport,'food-authenticity':bindAuthenticity,'smart-kitchen':bindKitchen,'creator-portal':bindCreator
    };map[id]?.();
  }
  async function compressImage(file){return new Promise((resolve,reject)=>{const img=new Image(),reader=new FileReader();reader.onerror=reject;reader.onload=()=>img.src=reader.result;img.onload=()=>{const max=640,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.7));};reader.readAsDataURL(file);});}
  async function bindBody(){
    $('#bodyProgressForm').addEventListener('submit',async e=>{e.preventDefault();const front=$('#bodyFront').files[0],side=$('#bodySide').files[0];if(!front&&!side&&!$('#bodyWeight').value&&!$('#bodyWaist').value)return toast('Add a photo or measurement');const entry={id:crypto.randomUUID(),date:$('#bodyDate').value||today(),weight:+$('#bodyWeight').value||0,waist:+$('#bodyWaist').value||0,note:$('#bodyNote').value};if(front)entry.front=await compressImage(front);if(side)entry.side=await compressImage(side);state.innovation.bodyProgress.unshift(entry);state.innovation.bodyProgress=state.innovation.bodyProgress.slice(0,20);addXP(10,'Progress entry');persist();openFeature('body-progress');toast('Private progress entry saved');});
    $$('[data-delete-body]').forEach(b=>b.onclick=()=>{state.innovation.bodyProgress=state.innovation.bodyProgress.filter(x=>x.id!==b.dataset.deleteBody);persist();openFeature('body-progress');});
  }
  function findFood(name){const t=String(name||'').toLowerCase();return allFoods().find(f=>f.name.toLowerCase()===t)||allFoods().find(f=>f.name.toLowerCase().includes(t)||t.includes(f.name.toLowerCase()));}
  function bindPortion(){const input=$('#portionImage');input.onchange=()=>{const f=input.files[0];if(!f)return;$('#portionPreview').src=URL.createObjectURL(f);$('#portionPreview').classList.remove('hidden');$('#portionPrompt').classList.add('hidden');};$('#estimatePortion').onclick=async()=>{const food=findFood($('#portionFood').value)||allFoods().find(f=>f.calories>0);const ref=$('#portionReference').value;let grams={card:180,spoon:120,fork:200,plate:280}[ref],confidence=68;let ai=null;if(input.files[0])try{const image=await compressImage(input.files[0]);const r=await fetch('/api/analyze-innovation-image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'portion',image,food:$('#portionFood').value,reference:ref})});if(r.ok)ai=await r.json();}catch{}if(ai?.grams){grams=ai.grams;confidence=ai.confidence||75;}const factor=grams/100,cal=Math.round((food.calories/Math.max(1,parseFloat(food.serving)||1))*(food.serving?.includes('100')?factor:Math.max(.5,grams/220)));$('#portionResult').innerHTML=`<div class="mega-result-card"><span>${food.emoji||'🍽️'}</span><div><small>ESTIMATED PORTION</small><h3>${esc(food.name)}</h3><p>${Math.round(grams)} g · about ${cal} kcal · ${confidence}% confidence</p></div><button id="savePortion" class="soft">Save</button></div>`;$('#savePortion').onclick=()=>{const ratio=cal/Math.max(1,food.calories);state.meals.push({...food,logId:crypto.randomUUID(),date:today(),mealType:'Lunch',portion:ratio,portionLabel:`${Math.round(grams)} g estimate`,calories:cal,protein:food.protein*ratio,carbs:food.carbs*ratio,fat:food.fat*ratio});addXP(15,'Portion scanned');save('Estimated portion added');};};}
  let arStream=null;
  async function startARCamera(){try{arStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});$('#arVideo').srcObject=arStream;await $('#arVideo').play();$('#arPlaceholder').classList.add('hidden');$('#captureAR').disabled=false;$('#stopAR').disabled=false;}catch{toast('Camera permission unavailable');}}
  function stopARCamera(){if(arStream){arStream.getTracks().forEach(t=>t.stop());arStream=null;}const v=$('#arVideo');if(v)v.srcObject=null;}
  function bindAR(){ $('#startAR').onclick=startARCamera;$('#stopAR').onclick=()=>{stopARCamera();$('#arPlaceholder').classList.remove('hidden');};$('#captureAR').onclick=async()=>{const v=$('#arVideo'),c=$('#arCanvas');c.width=v.videoWidth||640;c.height=v.videoHeight||480;c.getContext('2d').drawImage(v,0,0,c.width,c.height);const image=c.toDataURL('image/jpeg',.72);let items=[];try{const r=await fetch('/api/analyze-food',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image})});if(r.ok){const d=await r.json();items=(d.foods||[]).map(x=>findFood(x.name)).filter(Boolean);}}catch{}if(!items.length)items=allFoods().filter(f=>f.calories>100).slice(100,103);const f=items[0];$('#arOverlay').classList.remove('hidden');$('#arOverlay').innerHTML=`<b>${f.emoji||'🍽️'} ${esc(f.name)}</b><span>${f.calories} kcal · ${f.protein} g protein</span><button id="arAdd">Add</button>`;$('#arAdd').onclick=()=>{state.meals.push({...f,logId:crypto.randomUUID(),date:today(),mealType:'Lunch',portion:1,portionLabel:f.serving||'1 serving'});addXP(20,'AR scan');save('AR food added');};};}
  function parseMealText(text){const lower=text.toLowerCase();const matches=[];const sorted=[...allFoods()].sort((a,b)=>b.name.length-a.name.length);for(const f of sorted){if(lower.includes(f.name.toLowerCase())){let qty=1;const before=lower.slice(Math.max(0,lower.indexOf(f.name.toLowerCase())-15),lower.indexOf(f.name.toLowerCase()));if(/two|dua|2/.test(before))qty=2;if(/three|tiga|3/.test(before))qty=3;if(/half|separuh/.test(before))qty=.5;matches.push({food:f,qty});if(matches.length>=5)break;}}return matches;}
  function logParsed(matches,source){if(!matches.length)return toast('No matching food found. Try the exact food name.');matches.forEach(({food,qty})=>state.meals.push({...food,logId:crypto.randomUUID(),date:today(),mealType:'Lunch',portion:qty,portionLabel:`${qty} portion`,calories:food.calories*qty,protein:food.protein*qty,carbs:food.carbs*qty,fat:food.fat*qty}));state.innovation[source].unshift({date:new Date().toISOString(),text:matches.map(x=>`${x.qty} ${x.food.name}`).join(', ')});addXP(12,'Quick meal log');save(`${matches.length} food item(s) logged`);}
  function renderTextMatches(target,matches){$(target).innerHTML=matches.length?`<div class="text-match-list">${matches.map(x=>`<span>${x.food.emoji||'🍽️'} ${x.qty} × ${esc(x.food.name)}</span>`).join('')}</div>`:'<p class="mega-note">No database match yet.</p>';}
  function bindVoice(){const rec=window.SpeechRecognition||window.webkitSpeechRecognition;let recognition=null;if(rec){recognition=new rec();recognition.lang='en-MY';recognition.interimResults=true;recognition.onresult=e=>{$('#voiceTranscript').value=[...e.results].map(r=>r[0].transcript).join(' ');$('#voiceStatus').textContent='Listening…';$('#voiceOrb').classList.add('listening');};recognition.onend=()=>{$('#voiceOrb').classList.remove('listening');$('#voiceStatus').textContent='Review the transcript, then log it.';};}$('#startVoice').onclick=()=>recognition?recognition.start():toast('Speech recognition is not supported. Type the transcript manually.');$('#stopVoice').onclick=()=>recognition?.stop();$('#parseVoice').onclick=()=>{const m=parseMealText($('#voiceTranscript').value);renderTextMatches('#voiceMatches',m);logParsed(m,'voiceHistory');};renderMiniHistory('#voiceHistory',state.innovation.voiceHistory);}
  function bindWhatsApp(){$('#analyseWhatsApp').onclick=()=>{const text=$('#whatsappText').value,m=parseMealText(text);renderTextMatches('#whatsappMatches',m);logParsed(m,'whatsappHistory');};$('#openWhatsApp').onclick=()=>{const text=$('#whatsappText').value||'I ate nasi ayam and water.';window.open(`https://wa.me/?text=${encodeURIComponent(text+'\n\nPaste this back into MakanAI to log it.')}`,'_blank','noopener');};}
  function renderMiniHistory(sel,items){const el=$(sel);if(!el)return;el.innerHTML=items.length?items.slice(0,8).map(x=>`<div><span>${new Date(x.date).toLocaleDateString()}</span><b>${esc(x.text||x.name||'Entry')}</b></div>`).join(''):'<div class="empty">No entries yet.</div>';}
  function compatibleFood(f){const p=state.profile||{},txt=`${f.name} ${f.category}`.toLowerCase();if(p.dietStyle==='vegetarian'&&!f.vegetarian)return false;if(p.dietStyle==='vegan'&&(!f.vegetarian||/milk|egg|cheese|yogurt|chicken|fish|beef/.test(txt)))return false;if(p.dietStyle==='halal'&&/pork|bacon|ham|wine|beer/.test(txt))return false;return !String(p.allergy||'').toLowerCase().split(/[,;]/).filter(Boolean).some(a=>txt.includes(a.trim()));}
  function bindDelivery(){function run(){const maxCal=+$('#deliveryCalories').value,maxPrice=+$('#deliveryBudget').value;const foods=allFoods().filter(f=>f.calories>150&&f.calories<=maxCal&&compatibleFood(f)).sort((a,b)=>Math.abs(maxCal*.8-a.calories)-Math.abs(maxCal*.8-b.calories)).slice(0,8);$('#deliveryResults').innerHTML=foods.map((f,i)=>{const price=Math.min(maxPrice,Math.max(6,Math.round((f.calories/55+i)*2)/2)),fee=2.5+(i%3);return `<article><span>${f.emoji||'🍽️'}</span><h4>${esc(f.name)}</h4><p>${f.calories} kcal · ${f.protein} g protein</p><b>${money(price)} + ${money(fee)} delivery</b><button class="soft" data-delivery-food="${f.id}">Choose</button></article>`;}).join('')||'<div class="empty">No match. Increase calories or budget.</div>';$$('[data-delivery-food]').forEach(b=>b.onclick=()=>{const f=allFoods().find(x=>String(x.id)===b.dataset.deliveryFood);state.meals.push({...f,logId:crypto.randomUUID(),date:today(),mealType:$('#deliveryMeal').value,portion:1,portionLabel:f.serving});addXP(8,'Delivery choice');save('Delivery choice logged');});}$('#findDelivery').onclick=run;run();}
  function normalisePlate(){let v=+$('#vegSlider').value,p=+$('#proteinSlider').value,c=+$('#carbSlider').value,total=v+p+c||1;v=Math.round(v/total*100);p=Math.round(p/total*100);c=100-v-p;state.innovation.plate={veg:v,protein:p,carb:c};$('#vegValue').textContent=v+'%';$('#proteinValue').textContent=p+'%';$('#carbValue').textContent=c+'%';$('#plateVeg').style.flex=v;$('#plateProtein').style.flex=p;$('#plateCarb').style.flex=c;const score=Math.max(0,100-(Math.abs(v-50)+Math.abs(p-25)+Math.abs(c-25))*1.6);$('#plateScore').innerHTML=`<b>${Math.round(score)}/100 plate balance</b><span>${score>85?'Excellent balance':score>65?'Good start—adjust toward 50/25/25':'Try more vegetables and balanced protein/carbs'}</span>`;persist();}
  function bindPlate(){['#vegSlider','#proteinSlider','#carbSlider'].forEach(s=>$(s).oninput=normalisePlate);normalisePlate();$('#logPlate').onclick=()=>{const p=state.innovation.plate,cal=Math.round(420+(p.carb-25)*3+(p.protein-25)*2);state.meals.push({id:'smart-plate',name:'Smart Balanced Plate',category:'Custom',country:'MakanAI',emoji:'🍽️',serving:'1 plate',calories:cal,protein:Math.round(25+p.protein*.35),carbs:Math.round(45+p.carb*.6),fat:14,logId:crypto.randomUUID(),date:today(),mealType:'Lunch',portion:1,portionLabel:`${p.veg}/${p.protein}/${p.carb}`});addXP(18,'Plate built');save('Smart plate logged');};}
  function bindBattle(){$('#battleForm').onsubmit=e=>{e.preventDefault();state.innovation.battles.unshift({id:crypto.randomUUID(),friend:$('#battleFriend').value,type:$('#battleType').value,target:+$('#battleTarget').value,you:0,friendScore:0,date:new Date().toISOString()});persist();openFeature('nutrition-battle');};renderBattles();}
  function renderBattles(){const el=$('#battleList');if(!el)return;el.innerHTML=state.innovation.battles.length?state.innovation.battles.map(b=>`<article class="battle-card"><div><span>⚔️</span><div><b>You vs ${esc(b.friend)}</b><small>${esc(b.type)} · first to ${b.target}</small></div></div><div class="battle-score"><button data-battle-you="${b.id}">You ${b.you}</button><span>—</span><button data-battle-friend="${b.id}">${esc(b.friend)} ${b.friendScore}</button></div></article>`).join(''):'<div class="empty">No active battles.</div>';$$('[data-battle-you]').forEach(x=>x.onclick=()=>battlePoint(x.dataset.battleYou,'you'));$$('[data-battle-friend]').forEach(x=>x.onclick=()=>battlePoint(x.dataset.battleFriend,'friendScore'));}
  function battlePoint(id,key){const b=state.innovation.battles.find(x=>x.id===id);b[key]=Math.min(b.target,b[key]+1);if(key==='you'&&b.you===b.target)addXP(60,'Battle won');persist();renderBattles();}
  function petEmoji(){const p=state.innovation.pet;const base=p.stage>=4?'🐲':p.stage>=3?'🐶':p.stage>=2?'🐥':'🐣';return p.outfit==='crown'?`👑<br>${base}`:p.outfit==='cap'?`🧢<br>${base}`:p.outfit==='glasses'?`${base}🕶️`:base;}
  function bindPet(){$('#petName').onchange=()=>{state.innovation.pet.name=$('#petName').value||'Momo';persist();openFeature('virtual-pet');};$('#petOutfit').onchange=()=>{state.innovation.pet.outfit=$('#petOutfit').value;persist();openFeature('virtual-pet');};$$('[data-pet-action]').forEach(b=>b.onclick=()=>{const p=state.innovation.pet,a=b.dataset.petAction;if(a==='water'){p.energy=Math.min(100,p.energy+10);state.water=Math.min(state.waterGoal,state.water+1);}if(a==='fruit'){p.happiness=Math.min(100,p.happiness+12);p.energy=Math.min(100,p.energy+5);}if(a==='walk'){p.happiness=Math.min(100,p.happiness+10);p.energy=Math.max(0,p.energy-6);}if(a==='sleep')p.energy=Math.min(100,p.energy+20);p.stage=Math.min(4,1+Math.floor(((state.xp||0)+p.energy+p.happiness)/450));addXP(3,'Pet care');persist();openFeature('virtual-pet');});}
  function bindMood(){$('#moodForm').onsubmit=e=>{e.preventDefault();state.innovation.moods.unshift({id:crypto.randomUUID(),date:new Date().toISOString(),mood:new FormData(e.target).get('mood'),hunger:+$('#moodHunger').value,meal:$('#moodMeal').value,time:$('#moodTime').value,note:$('#moodNote').value});addXP(5,'Mood logged');persist();openFeature('mood-food');};renderMood();}
  function renderMood(){const list=state.innovation.moods;if(!$('#moodHistory'))return;const map={};list.forEach(x=>{map[x.mood]=(map[x.mood]||0)+1;});const top=Object.entries(map).sort((a,b)=>b[1]-a[1])[0];$('#moodSummary').innerHTML=top?`<div class="mega-insight"><b>Most logged context: ${esc(top[0])}</b><p>${top[1]} of ${list.length} entries. This is only a user-entered pattern, not a mental-health diagnosis.</p></div>`:'<div class="empty">Log several entries to see patterns.</div>';$('#moodHistory').innerHTML=list.slice(0,8).map(x=>`<div><span>${new Date(x.date).toLocaleDateString()}</span><b>${esc(x.mood)} · hunger ${x.hunger}/5 · ${esc(x.meal||'no meal')}</b></div>`).join('');}
  function bindSleep(){$('#sleepForm').onsubmit=e=>{e.preventDefault();state.innovation.sleep.unshift({date:new Date().toISOString(),hours:+$('#sleepHours').value,hunger:+$('#sleepHunger').value,snacks:+$('#sleepSnacks').value,bed:$('#sleepBed').value,wake:$('#sleepWake').value});addXP(5,'Sleep logged');persist();openFeature('sleep-hunger');};renderSleep();}
  function renderSleep(){const l=state.innovation.sleep;if(!$('#sleepAnalysis'))return;const avg=k=>l.length?l.reduce((a,x)=>a+x[k],0)/l.length:0;const short=l.filter(x=>x.hours<6.5),long=l.filter(x=>x.hours>=6.5),sn=a=>a.length?a.reduce((s,x)=>s+x.snacks,0)/a.length:0;$('#sleepAnalysis').innerHTML=l.length?`<div class="mega-insight"><b>Average sleep: ${avg('hours').toFixed(1)} hours</b><p>Average hunger ${avg('hunger').toFixed(1)}/5 and ${avg('snacks').toFixed(1)} snacks. ${short.length&&long.length?`Short-sleep days averaged ${sn(short).toFixed(1)} snacks versus ${sn(long).toFixed(1)} on longer-sleep days.`:'Add both shorter and longer sleep days for comparison.'}</p></div>`:'<div class="empty">No sleep logs yet.</div>';$('#sleepHistory').innerHTML=l.slice(0,8).map(x=>`<div><span>${new Date(x.date).toLocaleDateString()}</span><b>${x.hours} h · hunger ${x.hunger}/5 · ${x.snacks} snacks</b></div>`).join('');}
  function bindCycle(){$('#cycleEnabled').onchange=()=>{state.innovation.cycle.enabled=$('#cycleEnabled').checked;persist();openFeature('cycle-mode');};$('#cycleForm')?.addEventListener('submit',e=>{e.preventDefault();state.innovation.cycle.logs.unshift({date:new Date().toISOString(),day:+$('#cycleDay').value,phase:$('#cyclePhase').value,energy:+$('#cycleEnergy').value,craving:$('#cycleCraving').value});persist();openFeature('cycle-mode');});renderMiniHistory('#cycleHistory',state.innovation.cycle.logs.map(x=>({date:x.date,text:`Day ${x.day} · ${x.phase} · energy ${x.energy}/5 · ${x.craving||'no note'}`})));}
  function bindTravel(){$('#buildTravel').onclick=renderTravel;renderTravel();}
  function renderTravel(){const country=$('#travelCountry').value,need=$('#travelNeed').value,foods=allFoods().filter(f=>f.country===country).slice(0,8),phrases=TRAVEL_PHRASES[country]||TRAVEL_PHRASES.default;$('#travelGuide').innerHTML=`<div class="travel-pass"><div><span>DESTINATION</span><h3>${esc(country)}</h3><p>${esc(need.replace('-',' '))} guide</p></div><b>✈️</b></div><div class="mega-grid-2"><div><h4>Useful phrases</h4><div class="phrase-list">${phrases.map(p=>`<button data-copy-phrase="${esc(p)}">${esc(p)}</button>`).join('')}</div></div><div><h4>Popular foods in database</h4><div class="travel-foods">${foods.map(f=>`<span>${f.emoji||'🍽️'} ${esc(f.name)} · ${f.calories} kcal</span>`).join('')||'<p>No offline matches for this destination.</p>'}</div></div></div>`;$$('[data-copy-phrase]').forEach(b=>b.onclick=()=>{navigator.clipboard?.writeText(b.dataset.copyPhrase);toast('Phrase copied');});}
  function bindLeftover(){$('#generateLeftover').onclick=()=>{const selected=$$('.leftover-items input:checked').map(x=>x.value),manual=$('#leftoverManual').value.split(',').map(x=>x.trim()).filter(Boolean),items=[...selected,...manual];const names=items.length?items:['rice','egg','vegetables'];const ideas=[{name:`Quick ${names.slice(0,2).join(' & ')} Fried Rice`,emoji:'🥢',time:'15 min',cal:460},{name:`One-Pan ${names[0]} Bowl`,emoji:'🥘',time:'25 min',cal:420},{name:`Leftover ${names.slice(0,2).join(' ')} Wrap`,emoji:'🌯',time:'12 min',cal:380}];$('#leftoverResults').innerHTML=ideas.map(i=>`<article><span>${i.emoji}</span><h4>${esc(i.name)}</h4><p>${i.time} · about ${i.cal} kcal</p><b>Uses: ${esc(names.slice(0,4).join(', '))}</b><button class="soft" data-leftover-grocery>Add missing basics</button></article>`).join('');$$('[data-leftover-grocery]').forEach(b=>b.onclick=()=>{['onion','garlic','vegetables'].forEach(name=>{if(!state.grocery.some(g=>g.name===name))state.grocery.push({id:crypto.randomUUID(),name,done:false});});persist();toast('Basics added to grocery list');});};}
  function budgetSpent(){const manual=state.innovation.budget.manual.reduce((a,x)=>a+x.amount,0),receipts=(state.shop?.receipts||[]).filter(r=>Date.now()-new Date(r.date).getTime()<7*86400000).reduce((a,x)=>a+Number(x.total||0),0);return manual+receipts;}
  function bindBudget(){$('#budgetTarget').onchange=()=>{state.innovation.budget.target=+$('#budgetTarget').value||140;persist();renderBudget();};$('#budgetEntryForm').onsubmit=e=>{e.preventDefault();state.innovation.budget.manual.unshift({id:crypto.randomUUID(),date:new Date().toISOString(),name:$('#budgetEntryName').value,amount:+$('#budgetEntryAmount').value});persist();openFeature('budget-challenge');};renderBudget();}
  function renderBudget(){if(!$('#budgetSpent'))return;const spent=budgetSpent(),target=state.innovation.budget.target,pct=Math.min(100,spent/Math.max(1,target)*100);$('#budgetSpent').textContent=money(spent);$('#budgetRing').style.background=`conic-gradient(var(--primary) ${pct*3.6}deg,var(--line) 0)`;$('#budgetInsight').innerHTML=`<div class="mega-insight"><b>${money(Math.max(0,target-spent))} remaining</b><p>${pct<=70?'You are within the planned pace.':pct<=100?'Budget is getting close to the weekly limit.':'You are above the current target.'}</p></div>`;$('#budgetEntries').innerHTML=state.innovation.budget.manual.length?state.innovation.budget.manual.map(x=>`<div><span>${new Date(x.date).toLocaleDateString()}</span><b>${esc(x.name)} · ${money(x.amount)}</b></div>`).join(''):'<div class="empty">Receipt spending is included automatically. No manual entries yet.</div>';}
  function bindCampus(){const render=()=>{const term=$('#campusSearch').value.toLowerCase(),budget=+$('#campusBudget').value,queue=+$('#campusQueue').value;$('#campusGrid').innerHTML=CAMPUS_STALLS.filter(s=>(s.name+s.place).toLowerCase().includes(term)&&s.queue<=queue).map(s=>`<article class="campus-stall"><div><span>${s.emoji}</span><div><b>${esc(s.name)}</b><small>${esc(s.place)} · ${s.open?'Open':'Closed'} · queue ${s.queue} min</small></div></div>${s.foods.filter(f=>f[1]<=budget).map(f=>`<button data-campus-order="${s.id}|${esc(f[0])}|${f[1]}|${f[2]}" ${s.open?'':'disabled'}><span>${esc(f[0])}</span><b>${money(f[1])} · ${f[2]} kcal</b></button>`).join('')||'<p>No food under selected budget.</p>'}</article>`).join('');$$('[data-campus-order]').forEach(b=>b.onclick=()=>{const [stall,item,price,cal]=b.dataset.campusOrder.split('|');state.innovation.campusOrders.unshift({id:crypto.randomUUID(),date:new Date().toISOString(),stall,item,price:+price,cal:+cal,status:'Preparing'});addXP(5,'Campus preorder');persist();renderOrders();toast('Campus preorder created');});};function renderOrders(){$('#campusOrders').innerHTML=state.innovation.campusOrders.length?state.innovation.campusOrders.slice(0,8).map(x=>`<div><span>${new Date(x.date).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span><b>${esc(x.item)} · ${money(x.price)} · ${x.status}</b></div>`).join(''):'<div class="empty">No campus preorders.</div>';}['#campusSearch','#campusBudget','#campusQueue'].forEach(s=>$(s).oninput=render);render();renderOrders();}
  function bindQuiz(){renderQuiz();}
  function renderQuiz(){const qz=state.innovation.quiz,item=QUIZ[qz.index%QUIZ.length];$('#quizNumber').textContent=qz.index%QUIZ.length+1;$('#quizScore').textContent=qz.score;$('#quizBox').innerHTML=`<span class="quiz-category">QUESTION ${qz.index%QUIZ.length+1}</span><h3>${esc(item.q)}</h3><div class="quiz-options">${item.a.map((a,i)=>`<button data-quiz-answer="${i}">${esc(a)}</button>`).join('')}</div><div id="quizExplanation"></div>`;$$('[data-quiz-answer]').forEach(b=>b.onclick=()=>{const i=+b.dataset.quizAnswer,correct=i===item.c;if(correct){qz.score++;addXP(8,'Quiz answer');}$('#quizExplanation').innerHTML=`<div class="mega-insight ${correct?'good':'warn'}"><b>${correct?'Correct!':'Not quite.'}</b><p>${esc(item.e)}</p><button id="nextQuiz" class="soft">Next question</button></div>`;$$('[data-quiz-answer]').forEach(x=>x.disabled=true);$('#nextQuiz').onclick=()=>{qz.index=(qz.index+1)%QUIZ.length;persist();renderQuiz();};persist();});}
  function bindSafety(){const image=$('#safetyImage');$('#scanIngredients').onclick=async()=>{let text=$('#safetyText').value,ai=null;if(image.files[0])try{const img=await compressImage(image.files[0]);const r=await fetch('/api/analyze-innovation-image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'ingredients',image:img})});if(r.ok){ai=await r.json();text=[text,ai.ingredients].filter(Boolean).join(', ');$('#safetyText').value=text;}}catch{}const hits=SAFETY_RULES.filter(r=>r.term.test(text));$('#safetyResults').innerHTML=hits.length?`<div class="safety-list">${hits.map(h=>`<article class="${h.level}"><span>${h.level==='danger'?'⚠️':h.level==='warn'?'🔎':'ℹ️'}</span><div><b>${h.label}</b><small>Verify the exact ingredient and cross-contamination statement.</small></div></article>`).join('')}</div>`:'<div class="mega-insight good"><b>No configured keywords detected</b><p>This does not prove the product is free from allergens or unsuitable ingredients.</p></div>';addXP(5,'Ingredient check');};}
  function bindGroup(){$('#groupForm').onsubmit=e=>{e.preventDefault();state.innovation.groupMembers.push({id:crypto.randomUUID(),name:$('#groupName').value,preference:$('#groupPreference').value,allergy:$('#groupAllergy').value});persist();openFeature('group-ordering');};$('#matchGroup').onclick=renderGroupMatches;renderGroupMembers();}
  function renderGroupMembers(){if(!$('#groupMembers'))return;$('#groupMembers').innerHTML=state.innovation.groupMembers.length?`<div class="group-chips">${state.innovation.groupMembers.map(x=>`<span>${esc(x.name)} · ${esc(x.preference)}${x.allergy?` · avoid ${esc(x.allergy)}`:''}<button data-remove-member="${x.id}">×</button></span>`).join('')}</div>`:'<p class="mega-note">Add everyone’s requirements before matching a menu.</p>';$$('[data-remove-member]').forEach(b=>b.onclick=()=>{state.innovation.groupMembers=state.innovation.groupMembers.filter(x=>x.id!==b.dataset.removeMember);persist();openFeature('group-ordering');});}
  function renderGroupMatches(){const people=state.innovation.groupMembers,menu=state.shop?.menuResults?.length?state.shop.menuResults:allFoods().filter(f=>f.calories>200).slice(0,40);const ranked=menu.map(f=>{const text=`${f.name} ${f.description||''}`.toLowerCase();let okay=0;people.forEach(p=>{let good=true;if(/vegetarian/i.test(p.preference)&&!f.vegetarian)good=false;if(/vegan/i.test(p.preference)&&(!f.vegetarian||/milk|egg|chicken|fish/.test(text)))good=false;if(/halal/i.test(p.preference)&&/pork|bacon|ham|wine/.test(text))good=false;if(p.allergy&&text.includes(p.allergy.toLowerCase()))good=false;if(good)okay++;});return{f,okay};}).sort((a,b)=>b.okay-a.okay).slice(0,6);$('#groupResults').innerHTML=ranked.map(x=>`<article><span>${x.f.emoji||'🍽️'}</span><h4>${esc(x.f.name)}</h4><p>Suitable for ${x.okay}/${Math.max(1,people.length)} group members</p><b>${x.f.calories||'—'} kcal</b></article>`).join('');}
  function bindPassport(){$('#passportForm').onsubmit=async e=>{e.preventDefault();if(!$('#passportConsent').checked)return toast('Confirm consent before generating the QR card');const data={name:$('#passportName').value,language:$('#passportLanguage').value,allergy:$('#passportAllergy').value,diet:$('#passportDiet').value,contact:$('#passportContact').value};state.innovation.passport=data;persist();let qr='';try{const r=await fetch('/api/nutrition-passport-qr',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(r.ok)qr=(await r.json()).dataUrl;}catch{}$('#passportResult').innerHTML=`<div class="passport-card"><div><small>NUTRITION PASSPORT</small><h3>${esc(data.name||'Traveller')}</h3><p><b>Avoid:</b> ${esc(data.allergy||'Not specified')}</p><p><b>Diet:</b> ${esc(data.diet||'Not specified')}</p><p><b>Emergency:</b> ${esc(data.contact||'Not provided')}</p></div>${qr?`<img src="${qr}" alt="Nutrition passport QR">`:`<div class="qr-fallback">QR requires<br>npm server</div>`}</div>`;addXP(8,'Passport generated');};}
  function reportData(days){const cutoff=Date.now()-days*86400000,meals=state.meals.filter(m=>new Date(`${m.date}T12:00:00`).getTime()>=cutoff),cal=meals.reduce((a,x)=>a+Number(x.calories||0),0),protein=meals.reduce((a,x)=>a+Number(x.protein||0),0),moods=state.innovation.moods.filter(x=>new Date(x.date).getTime()>=cutoff);return{period:`Last ${days} days`,name:state.profile.name||'MakanAI user',target:state.target,meals:meals.length,averageCalories:Math.round(cal/days),averageProtein:Math.round(protein/days),waterGoal:state.waterGoal,currentWeight:state.weights?.[0]?.weight||state.profile.weight||'',moodEntries:moods.length,budgetSpent:budgetSpent(),generated:new Date().toLocaleString()};}
  function bindReport(){const render=()=>{const d=reportData(+$('#reportPeriod').value);$('#reportPreview').innerHTML=`<div class="report-sheet"><small>MAKANAI WORLD HEALTH SUMMARY</small><h3>${esc(d.period)}</h3><div>${[['Average calories',d.averageCalories+' kcal/day'],['Meals logged',d.meals],['Average protein',d.averageProtein+' g/day'],['Water goal',d.waterGoal+' glasses'],['Food spending',money(d.budgetSpent)],['Mood entries',d.moodEntries]].map(x=>`<span><b>${x[1]}</b><small>${x[0]}</small></span>`).join('')}</div><p>Generated ${esc(d.generated)}. Estimates are based on user-entered data.</p></div>`;};$('#reportPeriod').onchange=render;render();$('#downloadReport').onclick=async()=>{const d=reportData(+$('#reportPeriod').value);try{const r=await fetch('/api/health-report-pdf',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});if(!r.ok)throw Error();const blob=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='MakanAI-Health-Report.pdf';a.click();URL.revokeObjectURL(a.href);addXP(8,'Report generated');}catch{toast('PDF server unavailable. Use Print fallback.');}};$('#printReport').onclick=()=>{const w=window.open('','_blank');w.document.write(`<html><head><title>MakanAI Report</title><style>body{font-family:Arial;padding:40px}span{display:block;margin:10px}</style></head><body>${$('#reportPreview').innerHTML}</body></html>`);w.document.close();w.print();};}
  function inferAllergens(f){const t=`${f.name} ${f.category}`.toLowerCase(),a=[];if(/milk|cheese|yogurt|cream/.test(t))a.push('milk');if(/egg/.test(t))a.push('egg');if(/noodle|bread|pasta|cake|biscuit/.test(t))a.push('wheat/gluten');if(/prawn|shrimp|crab|lobster/.test(t))a.push('shellfish');if(/nut|satay/.test(t))a.push('nuts/peanuts');return a;}
  function bindAuthenticity(){$('#exploreFood').onclick=()=>{const f=findFood($('#authFood').value);if(!f)return toast('Food not found in the library');const allergens=inferAllergens(f),region=f.region||'Worldwide';$('#authResult').innerHTML=`<div class="auth-card"><div class="auth-head"><span>${f.emoji||'🍽️'}</span><div><small>${esc(f.country||'Worldwide')} · ${esc(region)}</small><h3>${esc(f.name)}</h3><p>${esc(f.category||'Food')}</p></div></div><div class="auth-grid"><article><b>Typical role</b><p>A dish or product associated with ${esc(f.country||'global')} food culture. Recipes vary by home, region and restaurant.</p></article><article><b>Common allergen clues</b><p>${allergens.length?esc(allergens.join(', ')):'No obvious clue from the name; verify ingredients.'}</p></article><article><b>Healthier preparation</b><p>Adjust portion, add vegetables, choose water and keep sauces or frying oil measured where appropriate.</p></article><article><b>Nutrition estimate</b><p>${f.calories} kcal · ${f.protein} g protein per ${esc(f.serving||'serving')}.</p></article></div></div>`;};}
  function bindKitchen(){$('#deviceForm').onsubmit=e=>{e.preventDefault();state.innovation.devices.push({id:crypto.randomUUID(),name:$('#deviceName').value,type:$('#deviceType').value,status:$('#deviceStatus').value,last:new Date().toISOString()});persist();openFeature('smart-kitchen');};renderDevices();$('#logScale').onclick=()=>{const f=findFood($('#scaleFood').value);if(!f)return toast('Select a food from the library');const grams=+$('#scaleReading').value,ratio=f.serving?.includes('100')?grams/100:grams/220;state.meals.push({...f,logId:crypto.randomUUID(),date:today(),mealType:'Lunch',portion:ratio,portionLabel:`${grams} g from smart scale`,calories:Math.round(f.calories*ratio),protein:f.protein*ratio,carbs:f.carbs*ratio,fat:f.fat*ratio});addXP(10,'Smart scale log');save('Smart scale food logged');};$('#startFryer').onclick=()=>{let sec=+$('#fryerMinutes').value*60;$('#kitchenStatus').innerHTML='<div class="mega-insight"><b id="timerText"></b><p>Demo timer runs while this workspace remains open.</p></div>';const timer=setInterval(()=>{sec--;const m=Math.floor(sec/60),s=sec%60;$('#timerText').textContent=`Air fryer: ${m}:${String(s).padStart(2,'0')}`;if(sec<=0){clearInterval(timer);toast('Air fryer timer complete');}},1000);};}
  function renderDevices(){if(!$('#deviceList'))return;$('#deviceList').innerHTML=state.innovation.devices.length?`<div class="device-grid">${state.innovation.devices.map(d=>`<article><span>${/scale/i.test(d.type)?'⚖️':/bottle/i.test(d.type)?'💧':/fridge/i.test(d.type)?'🧊':/fryer/i.test(d.type)?'🍟':'⌚'}</span><b>${esc(d.name)}</b><small>${esc(d.type)} · ${esc(d.status)}</small></article>`).join('')}</div>`:'<p class="mega-note">No devices paired. This prototype simulates integrations until real manufacturer APIs are connected.</p>';}
  function bindCreator(){$('#creatorForm').onsubmit=e=>{e.preventDefault();state.innovation.submissions.unshift({id:crypto.randomUUID(),date:new Date().toISOString(),type:$('#creatorType').value,creator:$('#creatorName').value,country:$('#creatorCountry').value,item:$('#creatorItem').value,calories:+$('#creatorCalories').value||0,price:+$('#creatorPrice').value||0,reference:$('#creatorReference').value,description:$('#creatorDescription').value,status:'Pending'});addXP(10,'Creator submission');persist();openFeature('creator-portal');};renderSubmissions();}
  function renderSubmissions(){if(!$('#submissionList'))return;$('#submissionList').innerHTML=state.innovation.submissions.length?state.innovation.submissions.map(s=>`<article class="submission-row"><div><span>${s.type==='Restaurant menu'?'🍽️':s.type==='Packaged product'?'📦':s.type==='Community recipe'?'👩‍🍳':'🎓'}</span><div><b>${esc(s.item)}</b><small>${esc(s.creator)} · ${esc(s.type)} · ${esc(s.status)}</small></div></div><div><button class="soft" data-approve-submission="${s.id}" ${s.status==='Approved'?'disabled':''}>Approve demo</button><button class="remove" data-delete-submission="${s.id}">×</button></div></article>`).join(''):'<div class="empty">No creator submissions.</div>';$$('[data-approve-submission]').forEach(b=>b.onclick=()=>{const s=state.innovation.submissions.find(x=>x.id===b.dataset.approveSubmission);s.status='Approved';if(s.calories&&!state.custom.some(x=>x.name===s.item))state.custom.push({id:`creator-${s.id}`,name:s.item,country:s.country,region:'Community',category:'Community Food',serving:'1 serving',calories:s.calories,protein:0,carbs:0,fat:0,sugar:0,sodium:0,emoji:'🍽️'});persist();openFeature('creator-portal');});$$('[data-delete-submission]').forEach(b=>b.onclick=()=>{state.innovation.submissions=state.innovation.submissions.filter(x=>x.id!==b.dataset.deleteSubmission);persist();openFeature('creator-portal');});}

  $('#closeInnovationModal').onclick=closeModal;$('#innovationModal').addEventListener('click',e=>{if(e.target===$('#innovationModal'))closeModal();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#innovationModal').classList.contains('hidden'))closeModal();});
  $('#innovationSearch').addEventListener('input',renderGrid);$$('#innovationFilters button').forEach(b=>b.onclick=()=>{$$('#innovationFilters button').forEach(x=>x.classList.toggle('active',x===b));renderGrid();});
  const oldGo=go;go=function(page){oldGo(page);if(page==='innovation')renderGrid();};
  if(!document.getElementById('foodNames')){const dl=document.createElement('datalist');dl.id='foodNames';dl.innerHTML=allFoods().slice(0,1600).map(f=>`<option value="${esc(f.name)}"></option>`).join('');document.body.appendChild(dl);}
  ensureMegaState();persist();renderGrid();
})();
